### ISSUE TITLE
Incompatibility with Browser: Table/Editor side-by-side (horizontal split)

### ISSUE THREAD

**Issue by Cupbox** [ijgnd/anki21__browser_card_info_bar#2]
Hello. With just this addon and Browser: Table/Editor side-by-side (horizontal split) enabled I get the following in my info bar
![image](https://user-images.githubusercontent.com/13769570/71415343-0f5b3c80-2653-11ea-9224-b38886479b35.png)

**Comment by ijgnd** [comment]
Thanks for your report.

When I made the "editor by the side" add-on three days ago the info bar was too wide according to my taste. So I made this narrower version. I forgot to include an option to make this narrow info bar optional. 

I just uploaded a new version to ankiweb. Could you update and try it out? For the moment I left the narrow info bar as the default when you also have "editor by the side" add-on so you need to adjust the add-on config once.

Does this solve your problem?

**Comment by Cupbox** [comment]
Yes, that fixes it. Thank you very much.
